export const PRODUCTS = [
  {
    id: 'p1',
    title: 'The White Nomad',
    artist: 'Lars Berg',
    price: 145,
    category: 'Fine Art Print',
    format: 'Portrait',
    technique: 'Giclée Print',
    description: 'An intimate portrait of an Arctic fox in a blizzard, captured in the heart of Svalbard.',
    aboutShot: 'This shot was taken during a late February expedition when the light barely touches the horizon. The fox was surprisingly curious, allowing for this close-up encounter.',
    image: 'https://images.unsplash.com/photo-1517783999520-f068d7431a60?auto=format&fit=crop&q=80&w=1200',
    tags: ['Arctic', 'Wildlife', 'Snow'],
  },
  {
    id: 'p2',
    title: 'Blue Hour Peaks',
    artist: 'Solveig Jensen',
    price: 380,
    category: 'Fine Art Print',
    format: 'Landscape',
    technique: 'Limited Edition',
    description: 'The sharp peaks of Senja island during the magical blue hour of midwinter.',
    aboutShot: 'Senja offers some of the most dramatic landscapes in Northern Norway. The blue hour here lasts for hours, providing a deep, ethereal light that is unique to the Arctic circle.',
    image: 'https://images.unsplash.com/photo-1534067783941-51c9c23ecefd?auto=format&fit=crop&q=80&w=1200',
    tags: ['Mountains', 'Blue Hour', 'Senja'],
  },
  {
    id: 'p3',
    title: 'Glacial Fragility',
    artist: 'Erik Foss',
    price: 295,
    category: 'Fine Art Print',
    format: 'Panorama',
    technique: 'Framed Print',
    description: 'Abstract patterns formed by melting sea ice in the Fram Strait.',
    aboutShot: 'As the climate changes, these patterns are becoming more transient. This photograph serves as both art and a document of a disappearing world.',
    image: 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&q=80&w=1200',
    tags: ['Ice', 'Abstract', 'Ocean'],
  },
  {
    id: 'p4',
    title: 'Aurora over Lyngen',
    artist: 'Maren Holm',
    price: 85,
    category: 'Poster',
    format: 'Landscape',
    technique: 'Digital Print',
    description: 'A vibrant display of the Northern Lights dancing over the Lyngen Alps.',
    aboutShot: 'The Lyngen Alps provide a perfect backdrop for the Aurora. This was a KP6 event, meaning the lights were visible even with significant moonlight.',
    image: 'https://images.unsplash.com/photo-1531366930477-4fbd093ceb11?auto=format&fit=crop&q=80&w=1200',
    tags: ['Aurora', 'Night', 'Lyngen'],
  },
  {
    id: 'p5',
    title: 'Coastal Silence',
    artist: 'Lars Berg',
    price: 25,
    category: 'Postcard',
    format: 'Portrait',
    technique: 'Premium Cardstock',
    description: 'A minimalist view of a traditional red rorbu (fisherman cabin) against a snowy backdrop.',
    aboutShot: 'Tromsø region is dotted with these iconic structures. They represent a century of survival in the harsh North.',
    image: 'https://images.unsplash.com/photo-1520645521318-f03a712f0e60?auto=format&fit=crop&q=80&w=1200',
    tags: ['Architecture', 'Tradition', 'Snow'],
  },
  {
    id: 'p6',
    title: 'Midnight Sun Horizon',
    artist: 'Solveig Jensen',
    price: 195,
    category: 'Fine Art Print',
    format: 'Landscape',
    technique: 'Giclée Print',
    description: 'The sun hovering just above the horizon at 2 AM in mid-July.',
    aboutShot: 'The Golden Hour that lasts all night. This was taken from the summit of Fløya, overlooking the Norwegian Sea.',
    image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&q=80&w=1200',
    tags: ['Sun', 'Summer', 'Sea'],
  }
];

export const CATEGORIES = ['All Art', 'Photographers', 'Postcards', 'Posters', 'The Arctic Story'];

export const FILTERS = {
  Technique: ['Fine Art Print', 'Poster', 'Postcard'],
  Format: ['Landscape', 'Portrait', 'Panorama'],
  Price: ['Under €50', '€50 - €200', 'Over €200']
};
